version: '3.9'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    restart: always
    network_mode: host
    pid: host
    environment:
      CLICKHOUSE_DB: default
      CLICKHOUSE_USER: anton
      CLICKHOUSE_PASSWORD: Aa3791
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    volumes:
      - clickhouse-data:/var/lib/clickhouse
      - clickhouse-logs:/var/log/clickhouse-server

volumes:
  clickhouse-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: './volume/data'

  clickhouse-logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: './volume/logs'
