version: '3.9'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    network_mode: host
    pid: host
    environment:
      MYSQL_ROOT_PASSWORD: Aa3791
    volumes:
      - mysql-data:/var/lib/mysql
      - type: bind
        source: ./volume/config/my.cnf
        target: /etc/my.cnf
        read_only: true

volumes:
  mysql-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: './volume/data'

  mysql-log:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: './volume/log'
