version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    network_mode: host
    pid: host
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Aa3791
    volumes:
      - postgres-data:/var/lib/postgresql/data
    command:
      - sh -c './prepare-volume.sh' # Running sh command during the lunch (need to be confirmed)

volumes:
  postgres-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: './volume/data'
