version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    network_mode: host
    pid: host
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Aa3791
    command:
      - '-c'
      - 'logging_collector=on'
      - '-c'
      - 'log_directory=/var/log/postgresql'
      - '-c'
      - 'log_file_mode=0640'
      - '-c'
      - 'log_min_messages=info'
      - '-c'
      - 'log_statement=all'
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - postgres-logs:/var/log/postgresql

volumes:
  postgres-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: './volume/data'

  postgres-logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: './volume/logs'
